from .dr_science import *
from .elon import *
from .elon2 import *
from .cpp_coding import *
from .react_template import *
from .rewoo_template import *
from .openai_template import *
from .vanilla_template import *
from .openai_memory_template import *
from .vanilla-ziyu import *
from .scholar-ziyu import *
from .agent_don import *
from .agent_don2 import *
from .kaykay import *
from .kaykay2 import *
from .cooldude import *
from .wiki import *
